In [191]:
import kagglehub
import os
import pandas as pd
import glob
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [192]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jessemostipak/hotel-booking-demand")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\naman yadav\.cache\kagglehub\datasets\jessemostipak\hotel-booking-demand\versions\1

In [193]:
# locate CSV(s) in the downloaded dataset folder and load the first one
files = glob.glob(os.path.join(path, '**', '*.csv'), recursive=True)
if not files:
    raise FileNotFoundError(f"No CSV files found in {path}")
print("Loading:", files[0])
df = pd.read_csv(files[0])

# show shape (attribute, not a method)
df.shape

Loading: C:\Users\naman yadav\.cache\kagglehub\datasets\jessemostipak\hotel-booking-demand\versions\1\hotel_bookings.csv

(119390, 32)

In [194]:
df.head(5)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [195]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 37.9 MB

In [196]:
df.describe(include='all')

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
count,119390,119390.000000,119390.000000,119390.000000,119390,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,...,119390,103050.000000,6797.000000,119390.000000,119390,119390.000000,119390.000000,119390.000000,119390,119390
unique,2,NaN,NaN,NaN,12,NaN,NaN,NaN,NaN,NaN,...,3,NaN,NaN,NaN,4,NaN,NaN,NaN,3,926
top,City Hotel,NaN,NaN,NaN,August,NaN,NaN,NaN,NaN,NaN,...,No Deposit,NaN,NaN,NaN,Transient,NaN,NaN,NaN,Check-Out,2015-10-21
freq,79330,NaN,NaN,NaN,13877,NaN,NaN,NaN,NaN,NaN,...,104641,NaN,NaN,NaN,89613,NaN,NaN,NaN,75166,1461
mean,NaN,0.370416,104.011416,2016.156554,NaN,27.165173,15.798241,0.927599,2.500302,1.856403,...,NaN,86.693382,189.266735,2.321149,NaN,101.831122,0.062518,0.571363,NaN,NaN
std,NaN,0.482918,106.863097,0.707476,NaN,13.605138,8.780829,0.998613,1.908286,0.579261,...,NaN,110.774548,131.655015,17.594721,NaN,50.535790,0.245291,0.792798,NaN,NaN
min,NaN,0.000000,0.000000,2015.000000,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,...,NaN,1.000000,6.000000,0.000000,NaN,-6.380000,0.000000,0.000000,NaN,NaN
25%,NaN,0.000000,18.000000,2016.000000,NaN,16.000000,8.000000,0.000000,1.000000,2.000000,...,NaN,9.000000,62.000000,0.000000,NaN,69.290000,0.000000,0.000000,NaN,NaN
50%,NaN,0.000000,69.000000,2016.000000,NaN,28.000000,16.000000,1.000000,2.000000,2.000000,...,NaN,14.000000,179.000000,0.000000,NaN,94.575000,0.000000,0.000000,NaN,NaN
75%,NaN,1.000000,160.000000,2017.000000,NaN,38.000000,23.000000,2.000000,3.000000,2.000000,...,NaN,229.000000,270.000000,0.000000,NaN,126.000000,0.000000,1.000000,NaN,NaN
max,NaN,1.000000,737.000000,2017.000000,NaN,53.000000,31.000000,19.000000,50.000000,55.000000,...,NaN,535.000000,543.000000,391.000000,NaN,5400.000000,8.000000,5.000000,NaN,NaN

In [197]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [198]:
df.duplicated().sum()

np.int64(31994)

In [199]:
df['hotel'].value_counts()

hotel
City Hotel      79330
Resort Hotel    40060
Name: count, dtype: int64

In [200]:
df['is_canceled'].value_counts()

is_canceled
0    75166
1    44224
Name: count, dtype: int64

In [201]:
df['is_canceled']=df['is_canceled'].replace({0: 'Not Canceled', 1: 'Canceled'}, inplace=True)

C:\Users\naman yadav\AppData\Local\Temp\ipykernel_24432\684446126.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['is_canceled']=df['is_canceled'].replace({0: 'Not Canceled', 1: 'Canceled'}, inplace=True)

In [202]:
df.rename(columns={
    'is_canceled': 'Booking Status',
    'hotel': 'Hotel',
    'lead_time':'Days_before_arrival',
    'arrival_date_year': 'Arrival Year',
    'arrival_date_month': 'Arrival Month',
    'arrival_date_week_number': 'Arrival Week',
    'arrival_date_day_of_month': 'Arrival Day',
    'stays_in_weekend_nights': 'Weekend Nights',
    'stays_in_week_nights': 'Week Nights',
    'Arrival_Period': 'Arrival Period',
    'adults': 'Adults',
    'children': 'Children',
    'babies': 'Babies',
    'meal': 'Meal Plan',
    'country': 'Country',
    'market_segment': 'Market Segment',
    'distribution_channel': 'Distribution Channel',
    'is_repeated_guest': 'Repeated Guest',
    'previous_cancellations': 'Previous Cancellations',
    'previous_bookings_not_canceled': 'Previous Bookings Not Canceled',
    'reserved_room_type': 'Reserved Room Type',
    'assigned_room_type': 'Assigned Room Type',
    'booking_changes': 'Booking Changes',
    'deposit_type': 'Deposit Type',
    'agent': 'Agent',
    'company': 'Company',
    'days_in_waiting_list': 'Days in Waiting List',
    'customer_type': 'Customer Type',
    'adr': 'Average Daily Rate (ADR)',
    'required_car_parking_spaces': 'Required Parking Spaces',
    'total_of_special_requests': 'Total Special Requests',
    'reservation_status': 'Reservation Status',
    'reservation_status_date': 'Reservation Status Date'

}, inplace=True)

In [203]:
df['Days_before_arrival'] = df['Days_before_arrival'].astype(str) + " days"

In [204]:
df['Arrival Year'].value_counts()

Arrival Year
2016    56707
2017    40687
2015    21996
Name: count, dtype: int64

In [205]:
df['Arrival Month'].value_counts()

Arrival Month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: int64

In [206]:
df['Arrival Week'].value_counts()

Arrival Week
33    3580
30    3087
32    3045
34    3040
18    2926
21    2854
28    2853
17    2805
20    2785
29    2763
42    2756
31    2741
41    2699
15    2689
27    2664
25    2663
38    2661
23    2621
35    2593
39    2581
22    2546
24    2498
13    2416
16    2405
19    2402
40    2397
26    2391
43    2352
44    2272
14    2264
37    2229
8     2216
36    2167
10    2149
9     2117
7     2109
12    2083
11    2070
45    1941
53    1816
49    1782
47    1685
46    1574
6     1508
50    1505
48    1504
4     1487
5     1387
3     1319
2     1218
52    1195
1     1047
51     933
Name: count, dtype: int64

In [207]:
import datetime

df["Arrival_Period"] = df["Arrival Week"].apply(
    lambda w: f"{datetime.date.fromisocalendar(2026, int(w), 1).strftime('%B %d')} – "
              f"{datetime.date.fromisocalendar(2026, int(w), 7).strftime('%B %d, %Y')}"
)

In [208]:
col = 'Week Nights' if 'Week Nights' in df.columns else 'stays_in_week_nights'
df.dropna(subset=[col], inplace=True)

In [209]:
df['Adults'].value_counts()

Adults
2     89680
1     23027
3      6202
0       403
4        62
26        5
27        2
20        2
5         2
40        1
50        1
55        1
6         1
10        1
Name: count, dtype: int64

In [210]:
df['Meal Plan'].value_counts()

Meal Plan
BB           92310
HB           14463
SC           10650
Undefined     1169
FB             798
Name: count, dtype: int64

In [211]:
df['Country'].value_counts()

Country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
NCL        1
KIR        1
SDN        1
ATF        1
SLE        1
Name: count, Length: 177, dtype: int64

In [212]:
df['Market Segment'].value_counts()

Market Segment
Online TA        56477
Offline TA/TO    24219
Groups           19811
Direct           12606
Corporate         5295
Complementary      743
Aviation           237
Undefined            2
Name: count, dtype: int64

In [213]:
df['Distribution Channel'].value_counts()

Distribution Channel
TA/TO        97870
Direct       14645
Corporate     6677
GDS            193
Undefined        5
Name: count, dtype: int64

In [214]:
df['Repeated Guest'].value_counts()

Repeated Guest
0    115580
1      3810
Name: count, dtype: int64

In [215]:
df['Repeated Guest'] = df['Repeated Guest'].replace({0: 'Not Repeated Guest', 1: 'Repeated Guest'})

In [216]:
df['Previous Cancellations'].value_counts()

Previous Cancellations
0     112906
1       6051
2        116
3         65
24        48
11        35
4         31
26        26
25        25
6         22
19        19
5         19
14        14
13        12
21         1
Name: count, dtype: int64

In [217]:
df['Reserved Room Type'].value_counts()

Reserved Room Type
A    85994
D    19201
E     6535
F     2897
G     2094
B     1118
C      932
H      601
P       12
L        6
Name: count, dtype: int64

In [218]:
df['Assigned Room Type'].value_counts()

Assigned Room Type
A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: count, dtype: int64

In [219]:
df['Booking Changes'].value_counts()

Booking Changes
0     101314
1      12701
2       3805
3        927
4        376
5        118
6         63
7         31
8         17
9          8
10         6
13         5
14         5
15         3
17         2
16         2
12         2
11         2
20         1
21         1
18         1
Name: count, dtype: int64

In [220]:
df['Children'].isnull().sum()

np.int64(4)

In [221]:
df['Children'] = df['Children'].fillna(0)

In [222]:
df['Children'].isnull().sum()

np.int64(0)

In [223]:
df['Country'] = df['Country'].fillna('Unknown', inplace=True)

C:\Users\naman yadav\AppData\Local\Temp\ipykernel_24432\1587427898.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Country'] = df['Country'].fillna('Unknown', inplace=True)

In [224]:
df['Country'].isnull().sum()

np.int64(0)

In [225]:
df['Agent'].value_counts()

Agent
9.0      31961
240.0    13922
1.0       7191
14.0      3640
7.0       3539
         ...
444.0        1
408.0        1
388.0        1
453.0        1
480.0        1
Name: count, Length: 333, dtype: int64

In [226]:
df['Agent'].isnull().sum()

np.int64(16340)

In [227]:
df['Agent'] = df['Agent'].replace({np.nan: 'Unknown'}, inplace=True)

C:\Users\naman yadav\AppData\Local\Temp\ipykernel_24432\1075643408.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Agent'] = df['Agent'].replace({np.nan: 'Unknown'}, inplace=True)

In [228]:
df.drop(columns=["Company"], inplace=True)

In [229]:
df['Days in Waiting List'].value_counts().sum()

np.int64(119390)

In [230]:
df['Customer Type'].value_counts()

Customer Type
Transient          89613
Transient-Party    25124
Contract            4076
Group                577
Name: count, dtype: int64

In [231]:
df['Required Car Parking Spaces'].value_counts()

KeyError: 'Required Car Parking Spaces'

In [ ]:
df['Total Special Requests'].value_counts()

Total Special Requests
0    70318
1    33226
2    12969
3     2497
4      340
5       40
Name: count, dtype: int64

In [ ]:
df['Reservation Status'].value_counts()

Reservation Status
Check-Out    75166
Canceled     43017
No-Show       1207
Name: count, dtype: int64

In [ ]:
df['Reservation Status'].isnull().sum()

np.int64(0)

In [ ]:
df.columns

Index(['Hotel', 'Booking Status', 'days_before_arrival', 'Arrival Year',
       'Arrival Month', 'Arrival Week', 'Arrival Day', 'Weekend Nights',
       'Week Nights', 'Adults', 'Children', 'Babies', 'Meal Plan', 'Country',
       'Market Segment', 'Distribution Channel', 'Repeated Guest',
       'Previous Cancellations', 'Previous Bookings Not Canceled',
       'Reserved Room Type', 'Assigned Room Type', 'Booking Changes',
       'Deposit Type', 'Agent', 'Days in Waiting List', 'Customer Type',
       'Average Daily Rate (ADR)', 'Required Car Parking Spaces',
       'Total Special Requests', 'Reservation Status',
       'Reservation Status Date', 'Arrival Period'],
      dtype='str')

In [ ]:
import pandas as pd

df.to_csv("hotel_bookings_cleaned.csv", index=False)

print("CSV exported successfully!")

CSV exported successfully!