In [25]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import os
import kagglehub

In [26]:

path = kagglehub.dataset_download("wenruliu/adult-income-dataset")
print("Path to dataset files:", path)
file_path = os.path.join(path, "adult.csv")
df = pd.read_csv(file_path)
print(df.shape)

Path to dataset files: C:\Users\naman yadav\.cache\kagglehub\datasets\wenruliu\adult-income-dataset\versions\2
(48842, 15)

In [27]:
df.shape

(48842, 15)

In [28]:
df.head(10)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
6,29,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,Male,0,0,40,United-States,<=50K
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
9,55,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States,<=50K

In [29]:
df.tail(10)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
48832,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
48833,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
48834,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
48835,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
48836,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [30]:
df.sample(10)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
13364,30,Local-gov,170772,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,United-States,<=50K
11594,21,Private,341368,HS-grad,9,Divorced,Craft-repair,Not-in-family,White,Male,0,0,20,United-States,<=50K
25356,36,Private,185360,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,60,United-States,<=50K
1785,26,Federal-gov,337575,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,United-States,>50K
47560,20,?,95989,Some-college,10,Never-married,?,Own-child,White,Female,0,0,40,United-States,<=50K
31220,20,?,424034,Some-college,10,Never-married,?,Own-child,White,Male,0,0,15,United-States,<=50K
30033,46,Private,181810,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,Black,Male,4064,0,40,United-States,<=50K
41568,51,Private,197163,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Female,0,2559,50,United-States,>50K
6179,29,Self-emp-not-inc,467936,Some-college,10,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,40,?,<=50K
46297,31,State-gov,440129,Some-college,10,Divorced,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,>50K

In [31]:
df.dtypes

age                int64
workclass            str
fnlwgt             int64
education            str
educational-num    int64
marital-status       str
occupation           str
relationship         str
race                 str
gender               str
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country       str
income               str
dtype: object

In [32]:
df['age'].isnull().sum()

np.int64(0)

In [33]:
df['age'].value_counts()

age
36    1348
35    1337
33    1335
23    1329
31    1325
      ...
88       6
85       5
87       3
89       2
86       1
Name: count, Length: 74, dtype: int64

In [34]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='str')

In [35]:
df.columns = df.columns.str.strip().str.upper()

In [36]:
df['WORKCLASS'].value_counts()

WORKCLASS
Private             33906
Self-emp-not-inc     3862
Local-gov            3136
?                    2799
State-gov            1981
Self-emp-inc         1695
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64

In [37]:
df['WORKCLASS']=df['WORKCLASS'].replace('?','Unknown')

In [38]:
df['EDUCATION'].value_counts()

EDUCATION
HS-grad         15784
Some-college    10878
Bachelors        8025
Masters          2657
Assoc-voc        2061
11th             1812
Assoc-acdm       1601
10th             1389
7th-8th           955
Prof-school       834
9th               756
12th              657
Doctorate         594
5th-6th           509
1st-4th           247
Preschool          83
Name: count, dtype: int64

In [39]:
df['EDUCATIONAL-NUM'].value_counts()

EDUCATIONAL-NUM
9     15784
10    10878
13     8025
14     2657
11     2061
7      1812
12     1601
6      1389
4       955
15      834
5       756
8       657
16      594
3       509
2       247
1        83
Name: count, dtype: int64

In [40]:
df['MARITAL-STATUS'].value_counts()

MARITAL-STATUS
Married-civ-spouse       22379
Never-married            16117
Divorced                  6633
Separated                 1530
Widowed                   1518
Married-spouse-absent      628
Married-AF-spouse           37
Name: count, dtype: int64

In [41]:
df['MARITAL-STATUS']=df['MARITAL-STATUS'].replace('Never-married','Unmarried')

In [44]:
df['OCCUPATION'].value_counts()

OCCUPATION
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Unknown              2809
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [43]:
df['OCCUPATION']=df['OCCUPATION'].replace('?','Unknown')

In [46]:
df.isnull().sum()

AGE                0
WORKCLASS          0
FNLWGT             0
EDUCATION          0
EDUCATIONAL-NUM    0
MARITAL-STATUS     0
OCCUPATION         0
RELATIONSHIP       0
RACE               0
GENDER             0
CAPITAL-GAIN       0
CAPITAL-LOSS       0
HOURS-PER-WEEK     0
NATIVE-COUNTRY     0
INCOME             0
dtype: int64

In [51]:
df = df.drop(columns=['RELATIONSHIP'])

In [52]:
df['RACE'].value_counts()

RACE
White                 41762
Black                  4685
Asian-Pac-Islander     1519
Amer-Indian-Eskimo      470
Other                   406
Name: count, dtype: int64

In [53]:
df['CAPITAL-GAIN'].value_counts()

CAPITAL-GAIN
0        44807
15024      513
7688       410
7298       364
99999      244
         ...
6612         1
1111         1
22040        1
1639         1
2387         1
Name: count, Length: 123, dtype: int64

In [54]:
df['HOURS-PER-WEEK'].value_counts()

HOURS-PER-WEEK
40    22803
50     4246
45     2717
60     2177
35     1937
      ...
79        1
69        1
87        1
94        1
82        1
Name: count, Length: 96, dtype: int64

In [58]:
df['NATIVE-COUNTRY'].value_counts()

NATIVE-COUNTRY
United-States                 43832
Mexico                          951
Unknown                         857
Philippines                     295
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Guatemala                        88
Poland                           87
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Nicaragua                        49
Greece                           49
Peru                             46
Ecuador                          45
France                           38
Ireland                          37
Thailand                         30
Hong                             30
Cambodia                         28
Trinadad&Tobago                  27
Laos                             23
Yugoslavia                       23
Outlying-US(Guam-USVI-etc)       23
Scotland                         21
Honduras                         20
Hungary                          19
Holand-Netherlands                1
Name: count, dtype: int64

In [57]:
df['NATIVE-COUNTRY']=df['NATIVE-COUNTRY'].replace('?','Unknown')

In [59]:
df['INCOME'].value_counts()

INCOME
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [64]:
df['INCOME'] = df['INCOME'].replace({
    '<=50K': 'LessThan-50K',
    '>50K': 'GreaterThan-50K'
})

In [65]:
import os

# Assuming df is your cleaned DataFrame
output_path = r"C:\Users\naman yadav\Desktop\New folder\eda_project\adult_income_clean.csv"

df.to_csv(output_path, index=False)

print("CSV file exported successfully to:", output_path)

CSV file exported successfully to: C:\Users\naman yadav\Desktop\New folder\eda_project\adult_income_clean.csv